name: pushstart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - uvicorn
  - fastapi
  - httpx
  - python-dotenv
  - pip:
    - mcp
    - todoist-api-python
    - dataclass-wizard==0.35.0
